---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: aws-deploy-
spec:
  inputs:
    resources:
    - name: repository
      resourceRef:
        name: klr-demo
  taskRef:
    name: serverless-deploy
