apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: aws-deploy
spec:
  taskSpec:
    steps:
    - name: deploy
      image: gcr.io/triggermesh/serverless
      args:
      - 'serverless'
      - 'deploy'
      env: 
      - name: AWS_ACCESS_KEY_ID
        valueFrom: 
          secretKeyRef: 
            name: awscreds
            key: aws_access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom: 
          secretKeyRef: 
            name: awscreds
            key: aws_secret_access_key
